"""empty message

Revision ID: 1fd63580ed02
Revises: 
Create Date: 2017-08-21 14:37:17.405915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fd63580ed02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('var_alarm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_id'], ['var_alarm_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'roles_users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.add_column(u'roles_users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'roles_users_ibfk_2', 'roles_users', type_='foreignkey')
    op.drop_constraint(u'roles_users_ibfk_1', 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'users', ['user_id'], ['id'])
    op.drop_column(u'roles_users', 'users_id')
    op.drop_column(u'roles_users', 'roles_id')
    op.add_column(u'var_alarm_log', sa.Column('status', sa.Integer(), nullable=True))
    op.drop_column(u'var_alarm_log', 'confirm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'var_alarm_log', sa.Column('confirm', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column(u'var_alarm_log', 'status')
    op.add_column(u'roles_users', sa.Column('roles_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column(u'roles_users', sa.Column('users_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.create_foreign_key(u'roles_users_ibfk_1', 'roles_users', 'roles', ['roles_id'], ['id'])
    op.create_foreign_key(u'roles_users_ibfk_2', 'roles_users', 'users', ['users_id'], ['id'])
    op.drop_column(u'roles_users', 'user_id')
    op.drop_column(u'roles_users', 'role_id')
    op.drop_table('var_alarm')
    # ### end Alembic commands ###
