"""empty message

Revision ID: 4893b31da873
Revises: d8c3464f6fd9
Create Date: 2017-08-15 15:55:44.160199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4893b31da873'
down_revision = 'd8c3464f6fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('var_alarm_log')
    op.drop_table('role_users')
    op.drop_table('role')
    op.drop_table('var_alarm_info')
    op.drop_constraint(u'variables_queries_ibfk_2', 'variables_queries', type_='foreignkey')
    op.drop_constraint(u'variables_queries_ibfk_1', 'variables_queries', type_='foreignkey')
    op.create_foreign_key(None, 'variables_queries', 'query_group', ['query_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'variables_queries', 'yjvariableinfo', ['variable_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variables_queries', type_='foreignkey')
    op.drop_constraint(None, 'variables_queries', type_='foreignkey')
    op.create_foreign_key(u'variables_queries_ibfk_1', 'variables_queries', 'query_group', ['query_id'], ['id'])
    op.create_foreign_key(u'variables_queries_ibfk_2', 'variables_queries', 'yjvariableinfo', ['variable_id'], ['id'])
    op.create_table('var_alarm_info',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('alarm_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('note', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('variable_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['variable_id'], [u'yjvariableinfo.id'], name=u'var_alarm_info_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('role',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('role_users',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], [u'role.id'], name=u'role_users_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'role_users_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('var_alarm_log',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('alarm_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('confirm', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alarm_id'], [u'var_alarm_info.id'], name=u'var_alarm_log_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
