"""empty message

Revision ID: bc8d94e4d701
Revises: f67517d0b893
Create Date: 2017-08-04 15:27:21.803462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc8d94e4d701'
down_revision = 'f67517d0b893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'yjvariableinfo_ibfk_2', 'yjvariableinfo', type_='foreignkey')
    op.drop_column('yjvariableinfo', 'plc_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yjvariableinfo', sa.Column('plc_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'yjvariableinfo_ibfk_2', 'yjvariableinfo', 'yjplcinfo', ['plc_id'], ['id'])
    # ### end Alembic commands ###
