"""empty message

Revision ID: d8c3464f6fd9
Revises: bc8d94e4d701
Create Date: 2017-08-04 18:10:40.287746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c3464f6fd9'
down_revision = 'bc8d94e4d701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('variables_queries',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['query_group.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['yjvariableinfo.id'], ),
    sa.PrimaryKeyConstraint('query_id', 'variable_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variables_queries')
    op.drop_table('role_users')
    # ### end Alembic commands ###
